language: node_js
node_js:
  - "stable"
cache:
  directories:
  - node_modules
deploy:
  provider: script
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: public
  keep_history: true
  on:
    branch: master
before_script:
  - "npm i -g gatsby"
  - "npm i"
script:
  - "npm run test"
after_success:
  - "npm run deploy"
